### ISSUE TITLE
Incorrect color when 10bit wide gamut monitor connect to PC through HDMI port which only support 8bit color

### ISSUE THREAD

**Issue by gky99** [ledoge/dwm_lut#7]
So I have one PC connecting to monitor A and B through DP ports. However, monitor A also connects to the same PC over an HDMI port with a KVM switch in between. Monitor A, therefore, is identified as two displays in the system, but as they are in duplicate mode, still shows same image.

Here comes the problem. When I have monitor A connects only through HDMI or DP, the 3dlut works great. But if I connect it through HDMI and DP at the same time, the color is washed out.

The color of monitor B is not affected though.

**Comment by ledoge** [comment]
Duplicate mode isn't really supported by the hook DLL, since the only way I found to distinguish between monitors is their desktop coordinates, which are identical for displays in a duplicate "group". Not sure what exactly happens in duplicate mode as I haven't been able to test it.

Washed out colors sounds like a typical symptom of black level mismatch, but I'm not sure why that would only manifest itself when using duplicate mode... Other than checking the HDMI black level on the GPU and monitor, I'm not sure what you could do.

**Comment by hyyz17200** [comment]
> I've further analyzed it. HDMI and DP output without 3dlut are correct. DP only with 3dlut is correct. HDMI only with 3dlut is washed out.
> 
> Duplicate DP and HDMI makes the washed-out output copied to DP output so DP also washed out. Extend DP and HDMI will have them act like using them alone, but disable HDMI still cause DP washed out.
> 
> HDMI black level setting on monitor doesn't seem to help. I didn't see how to change it on GPU. I want to mention that the DP output is 10bit and HDMI only 8bit. However, as I've tried to create the lut with HDMI only, and tested it HDMI only, but still get a washed-out picture, this probably not hurt anything.
> 
> Is there anything else I can do to identify the problem?

Probably the reason is more about the GPU driver.  Which manufacture do you have now?  Intel AMD Nvidia both have the range setting, and sometimes I have experienced the issue of detecting monitors as TV on all have them. You have to correct them manually.

Still, I have no idea why you were outputting simultaneously, the black lever is correct.

**Comment by gky99** [comment]
> 

It's an Nvidia card, and I'm pretty sure it's on the full range ( 0-255 ).
The reason I do that is just because I need to switch between computers while I'm working, but I sometimes want that full 10bit output when I'm not.

**Comment by gky99** [comment]
Actually, I bypass this problem by using a DP to HDMI 2.1 converter eventually. It's still on full range 8bit (cuz the monitor only supports HDMI 2.0) but the problem is gone.

**Comment by hyyz17200** [comment]
> Actually, I bypass this problem by using a DP to HDMI 2.1 converter eventually. It's still on full range 8bit (cuz the monitor only supports HDMI 2.0) but the problem is gone.

That's a great idea.  Maybe it's a nvidia bug, who knows.

**Comment by gky99** [comment]
> That's a great idea. Maybe it's a nvidia bug, who knows.

It seems to be something only tied to 10-bit wide gamut monitor with 8-bit signal over HDMI. Maybe someone also having a wide gamut monitor can test this and confirm my assumption.

**Comment by gky99** [comment]
Update, I don't experience the problem anymore. I'm not sure which part fixes the problem. It might be the driver update or the new HDMI cable.
